#!/bin/bash

# fix permissions
chown -R odroid:odroid /opt/navcoin-express
chmod 440 /etc/sudoers.d/navcoin-express

# reload systemctl daemon
systemctl daemon-reload

# enable navcoin-angular on boot
systemctl enable navcoin-express
systemctl start navcoin-express

echo
echo "Manage with: systemctl start|stop|restart navcoin-express"
echo
