#!/bin/bash

# required
set -e

# fix permissions
chown -R odroid:odroid /opt/navcoin-express

# reload systemctl daemon
systemctl daemon-reload

# enable navcoin-angular on boot
systemctl enable navcoin-express

echo
echo "Start with: systemctl start navcoin-express"
echo
