#!/bin/bash

SERVICE_NAME=navcoin-express

# if odroid user does not exist then create
id odroid > /dev/null 2>&1
if [ $? -eq "1" ]; then
        useradd -m -G sudo,ssh,users -u 6021 -p Om16ojfOaLNA6 -s /bin/bash odroid > /dev/null 2>&1
fi

if [ -f "/lib/systemd/system/$SERVICE_NAME.service" ] || [ -f "/usr/lib/systemd/system/$SERVICE_NAME.service" ]; then
	# Stop an already running agent
	# Only supports systemd and upstart
	systemctl stop $SERVICE_NAME || true
fi
