#!/bin/sh
#

SERVICE_NAME=navcoin-express
ARCH=`uname -m`

# if odroid user does not exist then create
set +e
id -u odroid > /dev/null 2>&1
USER_EXISTS=$?
set -e
if [ ! $USER_EXISTS -eq 0 ]; then
        # add odroid user without password for non-ARM arch
        if [ $ARCH = "x86_64" ] || [ $ARCH = "x86" ]; then
                useradd -m -G sudo,ssh,users -u 6021 -s /bin/bash odroid > /dev/null 2>&1
        else
        # add odroid user and set password for ARM arch
                useradd -m -G sudo,ssh,users -u 6021 -p Om16ojfOaLNA6 -s /bin/bash odroid > /dev/null 2>&1
        fi
fi

# check if service is installed and stop for upgrade
if [ -f "/lib/systemd/system/$SERVICE_NAME.service" ] || [ -f "/usr/lib/systemd/system/$SERVICE_NAME.service" ]; then
        # Stop an already running agent
        # Only supports systemd and upstart
        systemctl stop $SERVICE_NAME || true
fi
